package com.bithealth.common.cache.dao;

import com.bithealth.common.cache.model.CacheLog;
import com.bithealth.common.cache.model.CacheLogExample;
import com.bithealth.sdk.core.generic.GenericDao; 

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CacheLogMapper extends GenericDao<CacheLog, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int countByExample(CacheLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int deleteByExample(CacheLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int insert(CacheLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int insertSelective(CacheLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    List<CacheLog> selectByExample(CacheLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    CacheLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") CacheLog record, @Param("example") CacheLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int updateByExample(@Param("record") CacheLog record, @Param("example") CacheLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int updateByPrimaryKeySelective(CacheLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cache_log
     *
     * @mbggenerated Fri May 13 10:34:56 CST 2016
     */
    int updateByPrimaryKey(CacheLog record);
}