package com.bithealth.dataConversionServer.dao;

import com.bithealth.dataConversionServer.model.CenterConfig;
import com.bithealth.dataConversionServer.model.CenterConfigExample;
import com.bithealth.sdk.core.generic.GenericBaseDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CenterConfigMapper extends GenericBaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int countByExample(CenterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int deleteByExample(CenterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int insert(CenterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int insertSelective(CenterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    List<CenterConfig> selectByExample(CenterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    CenterConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") CenterConfig record, @Param("example") CenterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int updateByExample(@Param("record") CenterConfig record, @Param("example") CenterConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int updateByPrimaryKeySelective(CenterConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    int updateByPrimaryKey(CenterConfig record);
}