package com.bithealth.dataConversionServer.dao;

import com.bithealth.dataConversionServer.bean.ZUserInfo;
import com.bithealth.dataConversionServer.model.DataFileRelation;
import com.bithealth.dataConversionServer.model.DataFileRelationExample;
import com.bithealth.dataConversionServer.model.OrgidBean;
import com.bithealth.sdk.core.generic.GenericBaseDao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DataFileRelationMapper extends GenericBaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int countByExample(DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int deleteByExample(DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int insert(DataFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int insertSelective(DataFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    List<DataFileRelation> selectByExampleWithBLOBs(DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    List<DataFileRelation> selectByExample(DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    DataFileRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") DataFileRelation record, @Param("example") DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DataFileRelation record, @Param("example") DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByExample(@Param("record") DataFileRelation record, @Param("example") DataFileRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByPrimaryKeySelective(DataFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DataFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByPrimaryKey(DataFileRelation record);
    
    
    /** 
   	 * @Title: queryUserData 
   	 * @Description: 查询用户基本信息原始数据
   	 * @param dataFileRelation
   	 * @return    
   	 * @retrun List<DataFileRelation>
   	 */
   	public List<DataFileRelation> queryUserData(DataFileRelation dataFileRelation);
   	
   	/** 
	 * @Title: updataFileRelation 
	 * @Description:更新文件关联表 
	 * @param relation
	 * @return    
	 * @retrun int
	 */
	public int updataFileRelation(DataFileRelation relation);
	
	/** 
	 * @Title: queryOrgidList 
	 * @Description: 查询获取用户orgid List 
	 * @param list
	 * @return    
	 * @retrun List<OrgidBean>
	 */
	public List<OrgidBean> getOrgidList(List<ZUserInfo> list);
	
	 /** 
		 * @Title: saveUserData 
		 * @Description:  保存中联佳裕用户原始节本信息数据
		 * @return    
		 * @retrun int
		 */
		public int saveZLJYUserData(DataFileRelation dataFileRelation);
   	
}