package com.bithealth.dataConversionServer.dao;

import com.bithealth.dataConversionServer.model.RelationFailData;
import com.bithealth.dataConversionServer.model.RelationFailDataExample;
import com.bithealth.sdk.core.generic.GenericBaseDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationFailDataMapper extends GenericBaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int countByExample(RelationFailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int deleteByExample(RelationFailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int insert(RelationFailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int insertSelective(RelationFailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    List<RelationFailData> selectByExample(RelationFailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    RelationFailData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") RelationFailData record, @Param("example") RelationFailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByExample(@Param("record") RelationFailData record, @Param("example") RelationFailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByPrimaryKeySelective(RelationFailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_relation_fail
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    int updateByPrimaryKey(RelationFailData record);
    
    /** 
     * @Title: batchInsert 
     * @Description: 批量保存入库失败的会员数据 
     * @param list
     * @return    
     * @retrun int
     */
    int insertBatch(List<RelationFailData> list);
}