package com.bithealth.dataConversionServer.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CenterConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public CenterConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIvalidIpIsNull() {
            addCriterion("ivalid_ip is null");
            return (Criteria) this;
        }

        public Criteria andIvalidIpIsNotNull() {
            addCriterion("ivalid_ip is not null");
            return (Criteria) this;
        }

        public Criteria andIvalidIpEqualTo(String value) {
            addCriterion("ivalid_ip =", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpNotEqualTo(String value) {
            addCriterion("ivalid_ip <>", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpGreaterThan(String value) {
            addCriterion("ivalid_ip >", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpGreaterThanOrEqualTo(String value) {
            addCriterion("ivalid_ip >=", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpLessThan(String value) {
            addCriterion("ivalid_ip <", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpLessThanOrEqualTo(String value) {
            addCriterion("ivalid_ip <=", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpLike(String value) {
            addCriterion("ivalid_ip like", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpNotLike(String value) {
            addCriterion("ivalid_ip not like", value, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpIn(List<String> values) {
            addCriterion("ivalid_ip in", values, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpNotIn(List<String> values) {
            addCriterion("ivalid_ip not in", values, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpBetween(String value1, String value2) {
            addCriterion("ivalid_ip between", value1, value2, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIvalidIpNotBetween(String value1, String value2) {
            addCriterion("ivalid_ip not between", value1, value2, "ivalidIp");
            return (Criteria) this;
        }

        public Criteria andIpLimitIsNull() {
            addCriterion("ip_limit is null");
            return (Criteria) this;
        }

        public Criteria andIpLimitIsNotNull() {
            addCriterion("ip_limit is not null");
            return (Criteria) this;
        }

        public Criteria andIpLimitEqualTo(Integer value) {
            addCriterion("ip_limit =", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitNotEqualTo(Integer value) {
            addCriterion("ip_limit <>", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitGreaterThan(Integer value) {
            addCriterion("ip_limit >", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("ip_limit >=", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitLessThan(Integer value) {
            addCriterion("ip_limit <", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitLessThanOrEqualTo(Integer value) {
            addCriterion("ip_limit <=", value, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitIn(List<Integer> values) {
            addCriterion("ip_limit in", values, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitNotIn(List<Integer> values) {
            addCriterion("ip_limit not in", values, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitBetween(Integer value1, Integer value2) {
            addCriterion("ip_limit between", value1, value2, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andIpLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("ip_limit not between", value1, value2, "ipLimit");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNull() {
            addCriterion("company_code is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNotNull() {
            addCriterion("company_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeEqualTo(Integer value) {
            addCriterion("company_code =", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotEqualTo(Integer value) {
            addCriterion("company_code <>", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThan(Integer value) {
            addCriterion("company_code >", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_code >=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThan(Integer value) {
            addCriterion("company_code <", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThanOrEqualTo(Integer value) {
            addCriterion("company_code <=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIn(List<Integer> values) {
            addCriterion("company_code in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotIn(List<Integer> values) {
            addCriterion("company_code not in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeBetween(Integer value1, Integer value2) {
            addCriterion("company_code between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("company_code not between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andServiceUrlIsNull() {
            addCriterion("service_url is null");
            return (Criteria) this;
        }

        public Criteria andServiceUrlIsNotNull() {
            addCriterion("service_url is not null");
            return (Criteria) this;
        }

        public Criteria andServiceUrlEqualTo(String value) {
            addCriterion("service_url =", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlNotEqualTo(String value) {
            addCriterion("service_url <>", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlGreaterThan(String value) {
            addCriterion("service_url >", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("service_url >=", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlLessThan(String value) {
            addCriterion("service_url <", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlLessThanOrEqualTo(String value) {
            addCriterion("service_url <=", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlLike(String value) {
            addCriterion("service_url like", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlNotLike(String value) {
            addCriterion("service_url not like", value, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlIn(List<String> values) {
            addCriterion("service_url in", values, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlNotIn(List<String> values) {
            addCriterion("service_url not in", values, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlBetween(String value1, String value2) {
            addCriterion("service_url between", value1, value2, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andServiceUrlNotBetween(String value1, String value2) {
            addCriterion("service_url not between", value1, value2, "serviceUrl");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIsNull() {
            addCriterion("last_query_time is null");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIsNotNull() {
            addCriterion("last_query_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeEqualTo(Date value) {
            addCriterion("last_query_time =", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotEqualTo(Date value) {
            addCriterion("last_query_time <>", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeGreaterThan(Date value) {
            addCriterion("last_query_time >", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_query_time >=", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeLessThan(Date value) {
            addCriterion("last_query_time <", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_query_time <=", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIn(List<Date> values) {
            addCriterion("last_query_time in", values, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotIn(List<Date> values) {
            addCriterion("last_query_time not in", values, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeBetween(Date value1, Date value2) {
            addCriterion("last_query_time between", value1, value2, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_query_time not between", value1, value2, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeIsNull() {
            addCriterion("init_time is null");
            return (Criteria) this;
        }

        public Criteria andInitTimeIsNotNull() {
            addCriterion("init_time is not null");
            return (Criteria) this;
        }

        public Criteria andInitTimeEqualTo(Date value) {
            addCriterion("init_time =", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeNotEqualTo(Date value) {
            addCriterion("init_time <>", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeGreaterThan(Date value) {
            addCriterion("init_time >", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("init_time >=", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeLessThan(Date value) {
            addCriterion("init_time <", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeLessThanOrEqualTo(Date value) {
            addCriterion("init_time <=", value, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeIn(List<Date> values) {
            addCriterion("init_time in", values, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeNotIn(List<Date> values) {
            addCriterion("init_time not in", values, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeBetween(Date value1, Date value2) {
            addCriterion("init_time between", value1, value2, "initTime");
            return (Criteria) this;
        }

        public Criteria andInitTimeNotBetween(Date value1, Date value2) {
            addCriterion("init_time not between", value1, value2, "initTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeIsNull() {
            addCriterion("last_init_time is null");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeIsNotNull() {
            addCriterion("last_init_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeEqualTo(Date value) {
            addCriterion("last_init_time =", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeNotEqualTo(Date value) {
            addCriterion("last_init_time <>", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeGreaterThan(Date value) {
            addCriterion("last_init_time >", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_init_time >=", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeLessThan(Date value) {
            addCriterion("last_init_time <", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_init_time <=", value, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeIn(List<Date> values) {
            addCriterion("last_init_time in", values, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeNotIn(List<Date> values) {
            addCriterion("last_init_time not in", values, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeBetween(Date value1, Date value2) {
            addCriterion("last_init_time between", value1, value2, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastInitTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_init_time not between", value1, value2, "lastInitTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeIsNull() {
            addCriterion("last_get_time is null");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeIsNotNull() {
            addCriterion("last_get_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeEqualTo(Date value) {
            addCriterion("last_get_time =", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeNotEqualTo(Date value) {
            addCriterion("last_get_time <>", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeGreaterThan(Date value) {
            addCriterion("last_get_time >", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_get_time >=", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeLessThan(Date value) {
            addCriterion("last_get_time <", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_get_time <=", value, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeIn(List<Date> values) {
            addCriterion("last_get_time in", values, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeNotIn(List<Date> values) {
            addCriterion("last_get_time not in", values, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeBetween(Date value1, Date value2) {
            addCriterion("last_get_time between", value1, value2, "lastGetTime");
            return (Criteria) this;
        }

        public Criteria andLastGetTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_get_time not between", value1, value2, "lastGetTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 21 10:29:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}