package com.bithealth.dataConversionServer.model;

import com.bithealth.sdk.core.generic.GenericModel;
import java.util.Date;

public class CenterConfig extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.ivalid_ip
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String ivalidIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.ip_limit
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer ipLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.company_code
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.company_name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.service_url
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String serviceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.token
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.update_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.create_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.create_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.update_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastQueryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date initTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.last_init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastInitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_config.last_get_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastGetTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.id
     *
     * @return the value of data_center_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.id
     *
     * @param id the value for data_center_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.ivalid_ip
     *
     * @return the value of data_center_config.ivalid_ip
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getIvalidIp() {
        return ivalidIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.ivalid_ip
     *
     * @param ivalidIp the value for data_center_config.ivalid_ip
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setIvalidIp(String ivalidIp) {
        this.ivalidIp = ivalidIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.ip_limit
     *
     * @return the value of data_center_config.ip_limit
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getIpLimit() {
        return ipLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.ip_limit
     *
     * @param ipLimit the value for data_center_config.ip_limit
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setIpLimit(Integer ipLimit) {
        this.ipLimit = ipLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.company_code
     *
     * @return the value of data_center_config.company_code
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.company_code
     *
     * @param companyCode the value for data_center_config.company_code
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setCompanyCode(Integer companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.company_name
     *
     * @return the value of data_center_config.company_name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.company_name
     *
     * @param companyName the value for data_center_config.company_name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.service_url
     *
     * @return the value of data_center_config.service_url
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.service_url
     *
     * @param serviceUrl the value for data_center_config.service_url
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.token
     *
     * @return the value of data_center_config.token
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.token
     *
     * @param token the value for data_center_config.token
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.update_date
     *
     * @return the value of data_center_config.update_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.update_date
     *
     * @param updateDate the value for data_center_config.update_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.create_date
     *
     * @return the value of data_center_config.create_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.create_date
     *
     * @param createDate the value for data_center_config.create_date
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.create_by
     *
     * @return the value of data_center_config.create_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.create_by
     *
     * @param createBy the value for data_center_config.create_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.update_by
     *
     * @return the value of data_center_config.update_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.update_by
     *
     * @param updateBy the value for data_center_config.update_by
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.last_query_time
     *
     * @return the value of data_center_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastQueryTime() {
        return lastQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.last_query_time
     *
     * @param lastQueryTime the value for data_center_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastQueryTime(Date lastQueryTime) {
        this.lastQueryTime = lastQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.init_time
     *
     * @return the value of data_center_config.init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.init_time
     *
     * @param initTime the value for data_center_config.init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.last_init_time
     *
     * @return the value of data_center_config.last_init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastInitTime() {
        return lastInitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.last_init_time
     *
     * @param lastInitTime the value for data_center_config.last_init_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastInitTime(Date lastInitTime) {
        this.lastInitTime = lastInitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_config.last_get_time
     *
     * @return the value of data_center_config.last_get_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastGetTime() {
        return lastGetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_config.last_get_time
     *
     * @param lastGetTime the value for data_center_config.last_get_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastGetTime(Date lastGetTime) {
        this.lastGetTime = lastGetTime;
    }
}