package com.bithealth.dataConversionServer.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DataCenterAreaConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public DataCenterAreaConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("area_id like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("area_id not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeIsNull() {
            addCriterion("start_query_time is null");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeIsNotNull() {
            addCriterion("start_query_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeEqualTo(Date value) {
            addCriterion("start_query_time =", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeNotEqualTo(Date value) {
            addCriterion("start_query_time <>", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeGreaterThan(Date value) {
            addCriterion("start_query_time >", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_query_time >=", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeLessThan(Date value) {
            addCriterion("start_query_time <", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_query_time <=", value, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeIn(List<Date> values) {
            addCriterion("start_query_time in", values, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeNotIn(List<Date> values) {
            addCriterion("start_query_time not in", values, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeBetween(Date value1, Date value2) {
            addCriterion("start_query_time between", value1, value2, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andStartQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_query_time not between", value1, value2, "startQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeIsNull() {
            addCriterion("end_query_time is null");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeIsNotNull() {
            addCriterion("end_query_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeEqualTo(Date value) {
            addCriterion("end_query_time =", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeNotEqualTo(Date value) {
            addCriterion("end_query_time <>", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeGreaterThan(Date value) {
            addCriterion("end_query_time >", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_query_time >=", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeLessThan(Date value) {
            addCriterion("end_query_time <", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_query_time <=", value, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeIn(List<Date> values) {
            addCriterion("end_query_time in", values, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeNotIn(List<Date> values) {
            addCriterion("end_query_time not in", values, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeBetween(Date value1, Date value2) {
            addCriterion("end_query_time between", value1, value2, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andEndQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_query_time not between", value1, value2, "endQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIsNull() {
            addCriterion("last_query_time is null");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIsNotNull() {
            addCriterion("last_query_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeEqualTo(Date value) {
            addCriterion("last_query_time =", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotEqualTo(Date value) {
            addCriterion("last_query_time <>", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeGreaterThan(Date value) {
            addCriterion("last_query_time >", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_query_time >=", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeLessThan(Date value) {
            addCriterion("last_query_time <", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_query_time <=", value, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeIn(List<Date> values) {
            addCriterion("last_query_time in", values, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotIn(List<Date> values) {
            addCriterion("last_query_time not in", values, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeBetween(Date value1, Date value2) {
            addCriterion("last_query_time between", value1, value2, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_query_time not between", value1, value2, "lastQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeIsNull() {
            addCriterion("last_timing_query_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeIsNotNull() {
            addCriterion("last_timing_query_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeEqualTo(Date value) {
            addCriterion("last_timing_query_time =", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeNotEqualTo(Date value) {
            addCriterion("last_timing_query_time <>", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeGreaterThan(Date value) {
            addCriterion("last_timing_query_time >", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_timing_query_time >=", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeLessThan(Date value) {
            addCriterion("last_timing_query_time <", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_timing_query_time <=", value, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeIn(List<Date> values) {
            addCriterion("last_timing_query_time in", values, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeNotIn(List<Date> values) {
            addCriterion("last_timing_query_time not in", values, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeBetween(Date value1, Date value2) {
            addCriterion("last_timing_query_time between", value1, value2, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andLastTimingQueryTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_timing_query_time not between", value1, value2, "lastTimingQueryTime");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNull() {
            addCriterion("use_status is null");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNotNull() {
            addCriterion("use_status is not null");
            return (Criteria) this;
        }

        public Criteria andUseStatusEqualTo(Integer value) {
            addCriterion("use_status =", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotEqualTo(Integer value) {
            addCriterion("use_status <>", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusGreaterThan(Integer value) {
            addCriterion("use_status >", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_status >=", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusLessThan(Integer value) {
            addCriterion("use_status <", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusLessThanOrEqualTo(Integer value) {
            addCriterion("use_status <=", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusIn(List<Integer> values) {
            addCriterion("use_status in", values, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotIn(List<Integer> values) {
            addCriterion("use_status not in", values, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusBetween(Integer value1, Integer value2) {
            addCriterion("use_status between", value1, value2, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("use_status not between", value1, value2, "useStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIsNull() {
            addCriterion("last_send_time is null");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIsNotNull() {
            addCriterion("last_send_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeEqualTo(Date value) {
            addCriterion("last_send_time =", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotEqualTo(Date value) {
            addCriterion("last_send_time <>", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeGreaterThan(Date value) {
            addCriterion("last_send_time >", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_send_time >=", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeLessThan(Date value) {
            addCriterion("last_send_time <", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_send_time <=", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIn(List<Date> values) {
            addCriterion("last_send_time in", values, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotIn(List<Date> values) {
            addCriterion("last_send_time not in", values, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeBetween(Date value1, Date value2) {
            addCriterion("last_send_time between", value1, value2, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_send_time not between", value1, value2, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Integer value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Integer value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Integer value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Integer value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Integer value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Integer> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Integer> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Integer value1, Integer value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_area_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 21 10:29:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_center_area_config
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}