package com.bithealth.dataConversionServer.model;

import com.bithealth.sdk.core.generic.GenericModel;
import java.util.Date;

public class DataCenterAreaConfig extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.area_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.parent_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.start_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date startQueryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.end_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date endQueryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastQueryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.last_timing_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastTimingQueryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.use_status
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.create_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.update_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.last_send_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Date lastSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_area_config.source
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    private Integer source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.id
     *
     * @return the value of data_center_area_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.id
     *
     * @param id the value for data_center_area_config.id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.area_id
     *
     * @return the value of data_center_area_config.area_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.area_id
     *
     * @param areaId the value for data_center_area_config.area_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.parent_id
     *
     * @return the value of data_center_area_config.parent_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.parent_id
     *
     * @param parentId the value for data_center_area_config.parent_id
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.name
     *
     * @return the value of data_center_area_config.name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.name
     *
     * @param name the value for data_center_area_config.name
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.start_query_time
     *
     * @return the value of data_center_area_config.start_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getStartQueryTime() {
        return startQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.start_query_time
     *
     * @param startQueryTime the value for data_center_area_config.start_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setStartQueryTime(Date startQueryTime) {
        this.startQueryTime = startQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.end_query_time
     *
     * @return the value of data_center_area_config.end_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getEndQueryTime() {
        return endQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.end_query_time
     *
     * @param endQueryTime the value for data_center_area_config.end_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setEndQueryTime(Date endQueryTime) {
        this.endQueryTime = endQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.last_query_time
     *
     * @return the value of data_center_area_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastQueryTime() {
        return lastQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.last_query_time
     *
     * @param lastQueryTime the value for data_center_area_config.last_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastQueryTime(Date lastQueryTime) {
        this.lastQueryTime = lastQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.last_timing_query_time
     *
     * @return the value of data_center_area_config.last_timing_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastTimingQueryTime() {
        return lastTimingQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.last_timing_query_time
     *
     * @param lastTimingQueryTime the value for data_center_area_config.last_timing_query_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastTimingQueryTime(Date lastTimingQueryTime) {
        this.lastTimingQueryTime = lastTimingQueryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.use_status
     *
     * @return the value of data_center_area_config.use_status
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.use_status
     *
     * @param useStatus the value for data_center_area_config.use_status
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.create_time
     *
     * @return the value of data_center_area_config.create_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.create_time
     *
     * @param createTime the value for data_center_area_config.create_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.update_time
     *
     * @return the value of data_center_area_config.update_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.update_time
     *
     * @param updateTime the value for data_center_area_config.update_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.last_send_time
     *
     * @return the value of data_center_area_config.last_send_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Date getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.last_send_time
     *
     * @param lastSendTime the value for data_center_area_config.last_send_time
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setLastSendTime(Date lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_area_config.source
     *
     * @return the value of data_center_area_config.source
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_area_config.source
     *
     * @param source the value for data_center_area_config.source
     *
     * @mbggenerated Thu Jul 21 10:29:28 CST 2016
     */
    public void setSource(Integer source) {
        this.source = source;
    }
}