package com.bithealth.dataConversionServer.model;

import java.util.Date;

import javax.persistence.Entity;

import com.bithealth.sdk.core.generic.GenericModel;

@Entity
public class RelationFailData extends GenericModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.id
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.uniqueId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.idCard
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.msg
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.dataId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.createTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_center_relation_fail.updateTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.id
     *
     * @return the value of data_center_relation_fail.id
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.id
     *
     * @param id the value for data_center_relation_fail.id
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.uniqueId
     *
     * @return the value of data_center_relation_fail.uniqueId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.uniqueId
     *
     * @param uniqueid the value for data_center_relation_fail.uniqueId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.idCard
     *
     * @return the value of data_center_relation_fail.idCard
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.idCard
     *
     * @param idcard the value for data_center_relation_fail.idCard
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.msg
     *
     * @return the value of data_center_relation_fail.msg
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.msg
     *
     * @param msg the value for data_center_relation_fail.msg
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.dataId
     *
     * @return the value of data_center_relation_fail.dataId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public String getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.dataId
     *
     * @param dataid the value for data_center_relation_fail.dataId
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setDataid(String dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.createTime
     *
     * @return the value of data_center_relation_fail.createTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.createTime
     *
     * @param createtime the value for data_center_relation_fail.createTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_center_relation_fail.updateTime
     *
     * @return the value of data_center_relation_fail.updateTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_center_relation_fail.updateTime
     *
     * @param updatetime the value for data_center_relation_fail.updateTime
     *
     * @mbggenerated Tue Jul 19 10:54:01 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}